### ISSUE TITLE
New email adress won't be displayed after changing it.

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#21]
The LdapUser has to be refreshed after the email adress is changed, but I don't know how to access the UserProvider to call the method for refreshing.

**Comment by leomelzer** [comment]
@faboschert Symfony updates the attributes itself (by invalidating the session or something similar), the best way to solve this is by using [PRG](https://en.wikipedia.org/wiki/Post/Redirect/Get). I simply added a redirect to the member page itself so the new value will be displayed correctly. This also prevents the user from hitting refresh and thus issuing another POST request. 

Another way would be to set the authentication status of the token to false, see http://blogsh.de/2011/11/15/change-user-roles-during-a-session-in-symfony/ - but I think that wouldn't work for our current authentication provider, because we don't store the password itself in the session (which I think is good).

**Comment by faboschert** [comment]
Great, it works for me!
I guess you're right, assuming that unauthicating the user wouldn't work for us, but it would require the user to login again - not a nice way to change the password.
