### ISSUE TITLE
Returned LDAP data is limited to 500 entries

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#22]
As @faboschert noted, the LDAP response size is limited. To display all members on the group screen, we either need to:
1. Abstract the data loading and query on demand (e.g. show only all members and then load with the search box, maybe with the list.js pagination plugin?)
2. Increase the limit on the server

**Comment by faboschert** [comment]
I'd prefer option two for now. Firstly because it's easier and we could focus on more important things and secondly, because I think that the difference between the traffic volumes caused by each of the options could be less than one might think at the first look. If we decide to load the data dynamically, each search request will produce traffic (especially when the table should be reloaded when a new character is typed), the client won't be able to reuse data that is already downloaded from the server, because the filter logic runs on the server, and thus the users wouldn't be able to rush through the search entry that quickly. The only thing I'd load dynamically is - as you said - the loading of all data only after the filter "show group members" is unchecked. Apart from that I'd suggest to focus more on caching the data on the client and only update differences. But, as I mentioned before, I think the amount of data isn't a real concern for our case.

**Comment by leomelzer** [comment]
I increased the sizelimit attribute on the server to 2000, that should suffice for now. The change is also documented on the LDAP OA page.
