### ISSUE TITLE
Vision for the Dashboard

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#27]
@faboschert already had some nice ideas on how the Dashboard could evolve and form another integral part of the SOG infrastructure. Maybe you can post your ideas here? 

This issue should collect some interesting ideas so we or other people can get back to them but surely the functionality is not needed for launch. 

An easy one: group admins could post announcements which would be immediately visible to their respective group members up on login. Admins could do the same for all users.

**Comment by faboschert** [comment]
Due to the customizability of the dashboard, we could use it as a lobby for the members. For this the URL could be something like intern.ourdomain.com and the other systems would be accessable via intern.ourdomain.com/systemName. On the front page of the dashboard we could display things like the latest motivating intern news of our organisation and let everyone add a short news post, statistics or messages of the executive board. This would also give us the possibility to place e.g. the link to civi on a more prominent position than the tab in Open Atrium.

**Comment by leomelzer** [comment]
Just realized that when I read _Dashboard_ I also think of
- Announcements (e.g. Downtimes etc.)
- Stats (e.g. number of (active?) people in group)

**Comment by leomelzer** [comment]
Possibly: some kind of "job board" for small tasks which a free for any person to take on.

**Comment by faboschert** [comment]
Since we had to extend the ldap-adapter step by step, we should unify it in the future, meaning that we should chose between ou/uid and dn as a selector for entries. There are also some unused methods that could be removed. Another thing to think about is using searchEntries(...) from Zend\Ldap instead of search(...) to bypass using the Collection objects by returning arrays instead.

**Comment by leomelzer** [comment]
This project is deprecated and superseded by the much more awesome https://github.com/studieren-ohne-grenzen/vogelnest 🎉
