### ISSUE TITLE
Dashboard API

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#31]
Create a basic API through which other modules can trigger specific LDAP/dashboard related functions.
- add LDAP user (first to ou=inactive)
- request membership in group (including notification of group admin to reply)

The api should be easy to include from external php files. (e.g. OA LDAP sync, SOG membership registration module)

**Comment by leomelzer** [comment]
That would indeed make sense, good idea. 

We need to specify the methods and what they get as parameters:

# Add LDAP user
- **Input:** cn of User `string`, attributes of User `array` (TODO: specify), cn of home group `string`
- **Output:** `true` on success, `false` otherwise (or: Exception with message?)
- **Notes:**
  - Should check for duplicate, e.g. no two equal common names (How to deal with that? Append number?)
  - Send email to owner (What if multiple? All? Use e.g. berlin@sog.org?) of given home group to request manual approval, include link to dashboard
  - Email to user? Or does the respective module handle this on its own?

# Request membership in group
- **Input:** dn of User `string`, dn of Group `string`
- **Output:** `true` on success, `false` otherwise (or: Exception with message?)
- **Notes:**
  - Should check for duplicate, e.g. no two memberships in one group
  - Should check user is in `ou=active`, inactive users can't request memberships (Is this a valid constraint? We might want to add users to groups upon signup.)

Feel free to edit my post, I think everbody can because we're all owners of the organization.

**Comment by sleidig** [comment]
# Add LDAP user

## Input

(passed from sogintegration module, collected through registration form)
- firstname
- lastname
- email

## Details
- username + password should be generated by the dashboard API
- send password and username to new user (or maybe use existing functions for forgotten passwords?)
- send notification to group owner (only password, general greeting + information is handled through CiviCRM)
- add ldap user
- the sogintegration module calling this function also calls the api to request membership in group _allgemein_ and _lokalgruppe_. Or should the api just implicitly add new users accordingly?

# Concerning the API in general

Probably a php class that can be included and instanciated from other projects?

I can commit and transfer code from the sogintegration module for the needed ldap data fields, current email texts, etc.
But you should probably decide on the place for the api files first.

**Comment by leomelzer** [comment]
Thanks, that helps. @faboschert and I will discuss and follow up.

**Comment by leomelzer** [comment]
@sebastian-leidig See https://github.com/studieren-ohne-grenzen/dashboard/blob/api/app/sog/Tests/api.php
cc @faboschert 

This now works nicely, only two methods are directly exposed so far, `createMember` and `requestGroupMembership` - they do what you expect :)

I think sending mails to the group admin is still necessary, we can't expect them to check the dashboard every day. I included a link to the dashboard where they can review and activate the new members. 

Still to do:
1. Setup the `pending` attributes for our `ou`'s so we can store the membership requests (@kehrwoche?)
2. Decide how to store the `pending` requests for inactive (new) members: either with the true DN including the `ou=inactive` or the soon to be `ou=active` - up on activation we would need to rename the first solution while the latter produces (temporary) dead entries in the `pending` attributes. 
3. ~~We currently generate a random 8 character password which is included in the mail to the user, but how is the Drupal account assigned this password?~~ Stupid question. LDAP.

**Comment by leomelzer** [comment]
- [ ] Remove `mail-alias` due to changes #39

**Comment by leomelzer** [comment]
@faboschert What do you think about item 2? I'm not sure, storing the correct reference (with `ou=inactive`) seems better in my opinion. Then (up on activation) we'll need to query for all these stored references but that overhead is negligible, right?

**Comment by leomelzer** [comment]
Another option would be to not store the `ou=active` / `ou=inactive` with the groupOfNames fields but instead only `uid=foo,ou=people,o=sog-de,dc=sog` - don't know if this would break anything else? The scripts would have to be adapted as they currently use the immediate parent `ou=active` (default).

**Comment by sleidig** [comment]
are you allowed to skip parts of the dn in LDAP?

**Comment by sleidig** [comment]
Does `createMember` implicitly request memberships to the relevant groups (lg, allgemein)? Or should I call `requestGroupMembership` for those afterwards?

**Comment by leomelzer** [comment]
Yes, using `createMember` through the API will assign the two group memberships: see https://github.com/studieren-ohne-grenzen/dashboard/blob/api/app/sog/Api/SogDashboardApi.php#L69
Though this currently doesn't do anything because the `pending` fields for the groups are not yet in LDAP (who will do this? @kehrwoche?). But it's implemented like this, I'll change the comment of the method to reflect this behavior. 

In the API test.php requesting an additional group membership is shown (the method itself is public).

**Comment by leomelzer** [comment]
@sebastian-leidig Yeah, skipping parts isn't really a good idea...searching for the items would still work (scope: one/sub [0]), but the DN isn't recognized correctly then. So we should go with storing DNs with `ou=inactive` for inactive newly created members in the group `pending` fields - yes?

[0] https://technet.microsoft.com/en-us/library/cc978021.aspx

**Comment by sleidig** [comment]
I guess we can close this issue as the interfaces and basic functionalities are implemented. Specific bugs have separate issues.
