### ISSUE TITLE
Authentication system

### ISSUE THREAD

**Issue by faboschert** [studieren-ohne-grenzen/dashboard#4]
Implement the login system and make the rights of a user dependent on his role.

**Comment by leomelzer** [comment]
The basic authentication is now implemented, but isn't tested with our setup as of now. I don't know the actual password of any of the users yet.

**Comment by leomelzer** [comment]
@faboschert This should work properly as of de26d82

You can access the Security Token (the currently signed in user) with

``` php
var_dump($app['security.token_storage']->getToken());
```

Note that in routes which are not prefixed with `^/members` this will return an empty object. Shouldn't be a problem, can maybe be fixed by working with the pattern in `services.php:27`

You can change the password for your user using LAM or insert a new one for testing.
