### ISSUE TITLE
API createUser: Invalid dn in group's "pending"

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#46]
This is a minor issue with the API createUser / requestMembership.

For the group membership request of a newly created user the dn `uid=foo.bar,ou=active,ou=people,o=sog-de,dc=sog` is written to the groups "pending" list. 
But a new user is actually still under `ou=inactive`. So the LDAP record is pointing into the void until the user was activated.

It's maybe not worth fixing. But at least I want to document this here.

**Comment by sleidig** [comment]
Also see discussion https://github.com/studieren-ohne-grenzen/dashboard/issues/31

**Comment by leomelzer** [comment]
It's kinda documented inline, see https://github.com/studieren-ohne-grenzen/dashboard/blob/develop/app/sog/Dashboard/LdapAdapter.php#L294

Our options:
1. Leave as is and have (temporary) dead links in the tree
2. Have additional overhead (looping over all groups and changing the relevant ou=inactive to ou=active) but working links

**Comment by leomelzer** [comment]
I'd say this is not a blocker for #24 - moving this to milestone _next_
@faboschert What's your preferred solution to this (see my previous comment with two possible solutions)

**Comment by kehrwoche** [comment]
Would giving the absolute "path" to the user uid=foo.bar,ou=active,ou=people,o=sog-de,dc=sog instead of just foo.bar be another possible solution? I was thinking about this when implementing in OA since it would make our API more plain and simple. Especially when we also plan to use the API to add guests to a group.

**Comment by faboschert** [comment]
@kehrwoche @leomelzer I've added a function to the Ldap-Adapter for searching the dn of a given uid of a user. We now could require the dn to be given for all functions in the api and make the new function accessible over the api. Alternatively we could only require the dn for creating a new user and let the api search for the dn of the given uid in all other functions.
This would still lead to the problem leomelzer mentioned for 2. Nevertheless I like this solution better, because we could get the attributes (like name, email,...) of inactive users in the pending field more easily.

**Comment by sleidig** [comment]
I would tend towards "wontfix" for this as long as it doesn't get us in trouble anywhere in practice.

**Comment by leomelzer** [comment]
I chose to fix this for now because it makes things for activating new (inactive) members much much easier, it's implemented in af463aacf92d2ddb7aaf59ff423ccbca82610739

I use @faboschert's method for retrieving the full DN everytime I'm not certain, that doesn't happen in loops so should not be a concern for performance. Plus we get nicely linked (and valid) data. 

When a user is activated, I refresh the remaining `pending` requests by dropping them (old DN) and adding new ones (new DN). Could be in one method but I just went with the existing methods for simplicity. 

I think having the LdapAdapter / API decide on the exact location (relates to our internal LDAP structure) is a better solution than having external apps provide the location themselves. Otherwise the external apps would be tightly coupled to our internal LDAP setup, which is not so great.

If everyone is ok with this solution, I'll close this for now.
