### ISSUE TITLE
Who manages the standalone mailinglists?

### ISSUE THREAD

**Issue by leomelzer** [studieren-ohne-grenzen/dashboard#50]
We currently have the concept of group owner who manage the members of groups.

The standalone mailinglists under `ou=standalone-mailinglists,ou=groups,o=sog-de,dc=sog` don't have proper owners assigned ("admin") so don't show up for anyone to manage. 

For the time being the IT can handle this. For a long term solution, what should we do?
Introduce a new `ROLE_ADMIN` for ourselves so we can manage this or find respective coordinators among the members themselves?

cc @faboschert @sebastian-leidig

**Comment by sleidig** [comment]
We are currently also discussing whether all mailinglists should have a OA group. In that case, this question would become obsolete.

Otherwise, why don't we just assign some `admin` to `ou=standalone-mailinglists` entries when the list and its ldap record is created (i.e. the coordinator or whoever requested this new list and will manage it). That should allow them to manage through the dashboard, while assigning these admins should be a rare task and can be done by the IT through phpldapadmin.

**Comment by leomelzer** [comment]
Yes, let's see how we decide first. But I think having separate standalone mailing lists as you suggested makes somewhat sense, e.g. there is the "AG Events & Design" which clearly is an OA group (so currently it is also a mailing list) but there are separate lists for "events" and "design" (which should not show up in OA to avoid confusion). 

Let's see how everything plays out in practice.

**Comment by leomelzer** [comment]
This is basically resolved. The `ou=standalone-mailinglists` doesn't exist anymore, all groups are in `ou=groups` and a `uid=dashboardadmin` is owner of all groups as a fallback.
