### ISSUE TITLE
Password reset: display strength and meaningful error message

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#56]
The dashboard page to set a new password after the "forgot my password" e-mail does not show an indicator of the password strength (while the UI to change the password after logging in does).

More importantly: If the user submits a new password with less than 8 characters, only a generic error is displayed ("... nicht erfolgreich ..."). This should give meaningful feedback instead (or not allow setting of a short password in the first place).

**Comment by leomelzer** [comment]
Thanks for the suggestion, the latter was fixed in https://github.com/studieren-ohne-grenzen/dashboard/commit/049ffd4a5ee97c097737886b2dc4f42d554d77b7 but not yet deployed. 

We're not fully decided on which password meter to use yet, see #28 - when we make a decision there we will make sure to include it on the reset password page as well.
