### ISSUE TITLE
Make group selection for "Mitglieder verwalten" more prominent

### ISSUE THREAD

**Issue by sleidig** [studieren-ohne-grenzen/dashboard#59]
The dropdown to select the group, which is currently being managed at "Mitglieder verwalten" is very easily overlooked at the current position top right. This needs to be clearly visible.

Move this left aligned like to other text (and maybe below the heading?).

**Comment by leomelzer** [comment]
Hmm, I don't really have a good idea on how to improve this, but I'm biased because I designed it this way. I think it's a pretty standard pattern to switch accounts or similar and the control itself is visually present, good contrast and as well through the fixed positioning. There also is a note in the text on where to change it if someone doesn't see it. I'm open to concrete redesigns / suggestions though :)

**Comment by leomelzer** [comment]
cc @faboschert

**Comment by leomelzer** [comment]
Two suggestions:
<img width="1410" alt="screenshot 2015-09-03 12 05 56" src="https://cloud.githubusercontent.com/assets/23313/9655876/956a1de8-5234-11e5-99ee-fa5e02234b99.png">
<img width="1428" alt="screenshot 2015-09-03 12 07 40" src="https://cloud.githubusercontent.com/assets/23313/9655877/956e36b2-5234-11e5-8dbd-3218ece807c8.png">

**Comment by leomelzer** [comment]
@sebastian-leidig What do you think?

**Comment by sleidig** [comment]
I'd vote for the first suggestion. Aesthetically the second (and the original) may be a little better but having it aligned left is much more usable.

Thanks for putting in all this effort drafting solutions!

**Comment by leomelzer** [comment]
OK, thanks! I think so as well, maybe we'll find a better solution in the future. I'll commit the changes. No problem, Web Inspector ftw! :D
